- name: remove blue deployment
  hosts: all
  tasks:
   - name: delete blue pod
     shell:
      "kubectl delete deployment deployment-blue && kubectl delete svc deployment-blue"
     when: state  == "OPEN"

   - name: delete ingress
     shell:
      "kubectl delete ing deployment-canary-blue"
     when: state  == "OPEN"

   - name: update ingress to route all traffic to green
     shell:
      "kubectl apply -f /home/ubuntu/k8s/canary-release/ingress-canary-green.yaml"
     when: state  == "OPEN"

   - name: Update Problem card on Dynatrace
     uri:
       url: "{{ dtcommentapiurl }}"
       method: POST
       headers:
         Content-Type: "application/json"
         Authorization: "Api-Token {{ dttoken }}"
       status_code: 201
       body_format: json
       body:
         message: "Blue deployment has been deleted"
         context: "Ansible Tower"
     when: state  == "OPEN"
