- name: remove blue deployment
  hosts: all
  tasks:
   - name: delete blue pod
     shell:
      "kubectl delete deployment deployment-blue"

   - name: delete ingress
     shell:
      "kubectl delete ing deployment-canary-blue && kubectl delete svc deployment-blue"

   #- name: change folder to access yaml files
    # shell:
    #  "cd /home/ubuntu/k8s/canary-release/"

   - name: update ingress to route all traffic to green
     shell:
      "kubectl apply -f /home/ubuntu/k8s/canary-release/ingress-canary-green.yaml"
